config/routes.rb
Rails.application.routes.draw do
  get 'job/show'

  get 'job/create'

  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  root 'rooms#top'

    # get '/rooms/:id' => 'rooms#show',as: 'room'
 	# post '/rooms' => 'rooms#create'
 	# get '/rooms/' => 'rooms#index'
	resources :rooms ,only: [:show, :create, :game, :destroy] do
		  resources :chats, only: [:create]
      resources :joins, only: [:create,:destroy]
      resources :jobs, only: [:create]
      resources :roles, only: [:create]
      # resources :rolecards, only: [:create]		
	end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/haitoku.rb
class Haitoku < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/jinrou.rb
class Jinrou < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/join.rb
class Join < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/kariudo.rb
class Kariudo < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/kyojin.rb
class Kyojin < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/kyosin.rb
class Kyosin < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/kyoyu.rb
class Kyoyu < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/murabito.rb
class Murabito < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/neko.rb
class Neko < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/reino.rb
class Reino < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :chats
	has_many :joins , dependent: :destroy
	belongs_to :user
  has_many :jinrous, dependent: :destroy
  has_many :murabitos, dependent: :destroy
  has_many :kyoujins, dependent: :destroy
  has_many :kyousins, dependent: :destroy
  has_many :uras, dependent: :destroy
  has_many :reino, dependent: :destroy
  has_many :kariudo, dependent: :destroy
  has_many :nekos, dependent: :destroy
  has_many :kyoyus, dependent: :destroy
  has_many :youkos, dependent: :destroy
  has_many :haitokus, dependent: :destroy
end

app/models/ura.rb
class Ura < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chats
  has_many :rooms
  has_many :joins, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :jinrous, dependent: :destroy
  has_many :murabitos, dependent: :destroy
  has_many :kyoujins, dependent: :destroy
  has_many :kyousins, dependent: :destroy
  has_many :uras, dependent: :destroy
  has_many :reino, dependent: :destroy
  has_many :kariudo, dependent: :destroy
  has_many :nekos, dependent: :destroy
  has_many :kyoyus, dependent: :destroy
  has_many :youkos, dependent: :destroy
  has_many :haitokus, dependent: :destroy
end

app/models/youko.rb
class Youko < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def top
  	@rooms = Room.all
  	# @room = Room.find(params[:room_id])
  end 
  def create
  	@room = Room.new
  	@room.room_name = params[:room_name]
  	@room.room_content = params[:room_content]
    @room.user_id = current_user.id
  	@room.save
  	redirect_to root_path
  end
  def show
  	@room = Room.find(params[:id])
    @chats = Chat.where(room_id: params[:id])
    @user = current_user
    @join = current_user.joins.find_by!(room_id: @room.id)
    # @job = User.select(:name,:job,:room_id)
    # @GM = @job.where('GM', @room.id)
    # @PL = @job.where('PL', @room.id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<head>
	<%#=raw "<meta http-equiv='refresh' content='60'>" %>
</head>
<p>ここが<%= @room.room_name %>です </p>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
   <%= flash[:alert] %>
  </div>
<% end %>
 <table>
 	<% @chats.each do |chat| %>
 	<thead>
 		<tr>
 			<th><%= chat.id %></th>
 			<th><%= chat.name %> </th>
 			<th><%= chat.job %></th>
 			<th><p>画像</p></th>
 			<th><%= chat.content %></th>
 		</tr>
 	</thead>
 	<% end %>
 </table>
<%= form_tag(room_chats_path(@room.id)) do %>
 <p><%= current_user.name %><%= current_user.job %> 画像
 	<input type="text" name="content">
    <input type="submit" value="発言">
 </p>
<% end %>
<%#= link_to "役をつける",room_rolecards_path(@room.id), method: :post %>
<%= link_to "ゲームに参加する",room_jobs_path(@room.id), method: :post %>
<%= link_to "退出する",room_join_path(@join.room_id,@room.id), method: :delete %>

app/views/rooms/top.html.erb
<h1>ここがトップページです。</h1>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<h2>ルーム一覧</h2>
<table>
	  <thead>
    <tr>
      <th>部屋名</th>
      <th>説明</th>
    </tr>
  </thead>
	<% @rooms.each do |room| %>
  <thead>
  	<tr>
  		<th><%= link_to room.room_name, room_joins_path(room.id) ,method: :post %></th>
  		<th><%= room.room_content %></th>
  	</tr>
  </thead>

<% end %> 

<h2>新規ルーム作成</h2>

<%= form_tag rooms_path do %>
 <thead>
	<tr>
		<th><input type="text" name="room_name"></th>
		<th><input type="text" name="room_content"></th>
		<th><input type="submit" value="部屋を新規作成する"></th>
	</tr>
 </thead>
<% end %>
</table>

<div></div>